version: "3"
services:
  neuroapp:
    image: neuroapp:0.0.1
    volumes:
        - ${PWD}/log:/log
    container_name: neuroapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/neuroapp_db
    ports:
      - "8080:8080"
    restart: "no"
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=neuroapp_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: "no"
volumes:
  pgdata:
